<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-42ER5TB" name="com.hybridFramework.examples.VerifyProductsCount" tests="4" failures="0" timestamp="01 Apr 2018 02:57:41 GMT" time="0.015" errors="1">
  <testcase name="testVerifyProductsCount" time="0.015" classname="com.hybridFramework.examples.VerifyProductsCount">
    <skipped/>
  </testcase> <!-- testVerifyProductsCount -->
  <testcase name="testVerifyProductsCount" time="0.000" classname="com.hybridFramework.examples.VerifyProductsCount">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.hybridFramework.testBase.Config.getWebsite(Config.java:21)
	at com.hybridFramework.examples.VerifyProductsCount.testVerifyProductsCount(VerifyProductsCount.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testVerifyProductsCount -->
  <testcase name="testVerifyProductsCount" time="0.000" classname="com.hybridFramework.examples.VerifyProductsCount">
    <skipped/>
  </testcase> <!-- testVerifyProductsCount -->
  <testcase name="testVerifyProductsCount" time="0.000" classname="com.hybridFramework.examples.VerifyProductsCount">
    <skipped/>
  </testcase> <!-- testVerifyProductsCount -->
</testsuite> <!-- com.hybridFramework.examples.VerifyProductsCount -->
